version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: 456433063024.dkr.ecr.us-east-2.amazonaws.com/datascience/k8s-argocd-demo-app
    env_file:
      - .env
    ports:
      - '8000:8000'
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    restart: unless-stopped
