apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: argocd-demo-hpa
  namespace: argocd-demo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: argocd-demo
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 2