apiVersion: v1
kind: Namespace
metadata:
  labels:
    name: kustomizatoin-demo
  name: kustomization-demo
---
apiVersion: v1
kind: Service
metadata:
  name: ds-demo-kustomizatoin-demo-svc
  namespace: kustomization-demo
spec:
  ports:
  - nodePort: 30083
    port: 8000
    targetPort: 8000
  selector:
    app: kustomizatoin-demo
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kustomizatoin-demo
  name: ds-demo-kustomizatoin-demo
  namespace: kustomization-demo
spec:
  replicas: 4
  selector:
    matchLabels:
      app: kustomizatoin-demo
  template:
    metadata:
      labels:
        app: kustomizatoin-demo
    spec:
      containers:
      - image: 456433063024.dkr.ecr.us-east-2.amazonaws.com/datascience/k8s-argocd-demo-app:latest
        imagePullPolicy: IfNotPresent
        name: kustomizatoin-demo
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 500m
            memory: 256Mi
      imagePullSecrets:
      - name: ecr-registry
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ds-demo-kustomizatoin-demo-hpa
  namespace: kustomization-demo
spec:
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 2
        type: Utilization
    type: Resource
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ds-demo-kustomizatoin-demo
