apiVersion: apps/v1
kind: Deployment
metadata:
  name: kustomization-demo
  labels:
    app: kustomization-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kustomization-demo
  template:
    metadata:
      labels:
        app: kustomization-demo
    spec:
      imagePullSecrets:
        - name: ecr-registry
      containers:
        - name: kustomization-demo
          image: 456433063024.dkr.ecr.us-east-2.amazonaws.com/datascience/k8s-argocd-demo-app:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          resources:
            requests:
              cpu: "500m"    # reserve 0.5 CPU core
              memory: "256Mi"   # reserve 256 MiB RAM
            limits:
              cpu: "1"       # cap at 1 CPU core
              memory: "512Mi"   # cap at 512 MiB RAM

